name: teocatapp
description: Aplicación móvil para gestión de TeoCat

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  intl: ^0.20.2
  flutter_secure_storage: ^8.0.0
  http: ^1.4.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  lottie: ^2.7.0
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^29.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
